### ISSUE TITLE
Top 10 Annotations

### ISSUE THREAD

**Issue by kamahmad** [nicholasbergesen/octo-analytics#5]
```
SELECT message, COUNT(message) AS "value_occurrence"
FROM  hive.snapshots_presto.check_annotations
GROUP BY message
ORDER BY "value_occurrence" DESC
LIMIT 10;
```

1 | UHJvY2VzcyBjb21wbGV0ZWQgd2l0aCBleGl0IGNvZGUgMS4= | 224500886
-- | -- | --
2 | VWJ1bnR1LWxhdGVzdCB3b3JrZmxvd3Mgd2lsbCB1c2UgVWJ1bnR1LTIwLjA0IHNvb24uIEZvciBtb3JlIGRldGFpbHMsIHNlZSBodHRwczovL2dpdGh1Yi5jb20vYWN0aW9ucy92aXJ0dWFsLWVudmlyb25tZW50cy9pc3N1ZXMvMTgxNg== | 187398129
3 | VGhlIG9wZXJhdGlvbiB3YXMgY2FuY2VsZWQu | 88619573
4 | VGhpcyByZXF1ZXN0IHdhcyBhdXRvbWF0aWNhbGx5IGZhaWxlZCBiZWNhdXNlIHRoZXJlIHdlcmUgbm8gZW5hYmxlZCBydW5uZXJzIG9ubGluZSB0byBwcm9jZXNzIHRoZSByZXF1ZXN0IGZvciBtb3JlIHRoYW4gMSBkYXlzLg== | 49354506
5 | InZpcnR1YWwiIGlzIHJlZHVuZGFudCBzaW5jZSBmdW5jdGlvbiBpcyBhbHJlYWR5IGRlY2xhcmVkIGFzICJvdmVycmlkZSIgKHJlYWRhYmlsaXR5L2luaGVyaXRhbmNlKQ== | 49006201
6 | VGhlIGpvYiB3YXMgbm90IHN0YXJ0ZWQgYmVjYXVzZSByZWNlbnQgYWNjb3VudCBwYXltZW50cyBoYXZlIGZhaWxlZC4gUGxlYXNlIGVuc3VyZSBwYXltZW50IGluIG9yZGVyIHRvIHByb2NlZWQu | 47403683
7 | bGluZSB0b28gbG9uZyA= | 43257021
8 | UHJvY2VzcyBjb21wbGV0ZWQgd2l0aCBleGl0IGNvZGUgMi4= | 38987929
9 | Q29tcGxleCBNZXRob2Q= | 33172339
10 | UGxlYXNlIHZlcmlmeSB5b3VyIGVtYWlsIGFkZHJlc3MgdG8gcnVuIEdpdEh1YiBBY3Rpb25zIHdvcmtmbG93cy4gaHR0cHM6Ly9naXRodWIuY29tL3NldHRpbmdzL2VtYWlscw==

**Comment by nicholasbergesen** [comment]
Thank you @kamahmad
